### ISSUE TITLE
Nil URL error; sample Nginx configuration

### ISSUE THREAD

**Issue by sudoman** [eriko/discourse_cas_sso#11]
Hello eriko,

It looks like I managed to get the Nginx reverse proxy (at least partly) working. This is what I'm using for anyone who's interested:

````
        location /sso {
                proxy_pass http://localhost:3001/;
                proxy_set_header Host $http_host;
                proxy_http_version 1.1;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto https;
        }
        location ~ ^/auth/cas {
                proxy_pass http://localhost:3001$1;
                proxy_set_header Host $http_host;
                proxy_http_version 1.1;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto https;
        }
````

It might be nice to share this config or one like it in the README once I am sure that it's working properly.

However it looks like there is an error on the `/auth/cas/callback` page:

````
I, [2018-09-04T15:49:43.614713 #23861]  INFO -- : Started GET "/" for REDACTED_IP_ADDR at 2018-09-04 15:49:43 -0400
I, [2018-09-04T15:49:43.616753 #23861]  INFO -- : Processing by LoginController#login as HTML
I, [2018-09-04T15:49:43.617998 #23861]  INFO -- : Redirected to https://example.com/auth/cas
I, [2018-09-04T15:49:43.618383 #23861]  INFO -- : Completed 302 Found in 1ms (ActiveRecord: 0.0ms)
I, [2018-09-04T15:49:43.697060 #23861]  INFO -- : Started GET "/auth/cas" for REDACTED_IP_ADDR at 2018-09-04 15:49:43 -0400
I, [2018-09-04T15:49:44.055583 #23861]  INFO -- : Started GET "/auth/cas/callback?url&ticket=ST-1536090683rUevxQ7nlb1Cyf1JmHk" for REDACTED_IP_ADDR at 2018-09-04 15:49:44 -0400
I, [2018-09-04T15:49:44.092010 #23861]  INFO -- : Processing by LoginController#create as HTML
I, [2018-09-04T15:49:44.092448 #23861]  INFO -- :   Parameters: {"url"=>nil, "ticket"=>"ST-1536090683rUevxQ7nlb1Cyf1JmHk", "provider"=>"cas"}
I, [2018-09-04T15:49:44.093422 #23861]  INFO -- : Completed 500 Internal Server Error in 1ms (ActiveRecord: 0.0ms)
F, [2018-09-04T15:49:44.094732 #23861] FATAL -- :   
F, [2018-09-04T15:49:44.094913 #23861] FATAL -- : TypeError (no implicit conversion of nil into String):
F, [2018-09-04T15:49:44.095053 #23861] FATAL -- :   
F, [2018-09-04T15:49:44.095199 #23861] FATAL -- : lib/single_sign_on.rb:72:in `hexdigest'
F, [2018-09-04T15:49:44.095332 #23861] FATAL -- : lib/single_sign_on.rb:72:in `sign'
F, [2018-09-04T15:49:44.095559 #23861] FATAL -- : lib/single_sign_on.rb:24:in `parse'
F, [2018-09-04T15:49:44.095759 #23861] FATAL -- : app/controllers/login_controller.rb:20:in `create'
````

https://github.com/eriko/discourse_cas_sso/blob/master/app/controllers/login_controller.rb

There is a GET parameter "?url" that has no value. Is this supposed to be the return url set by Discourse when it redirects the user to the CAS SSO application? I haven't switched over the site to use SSO yet, but was just testing it out for now. Next up, I'll try enabling SSO on Discourse.

Thanks,
Andrew

**Comment by eriko** [comment]
You are correct the url parameter is sent by the discourse instance.  This allows the discourse instance to tell the SSO provider (this app) where to return to after authentication.  This allows more than one discourse instance to use the same SSO provider.
